const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Json,
		C3.Plugins.Dictionary,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Behaviors.Timer,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Particles,
		C3.Behaviors.skymenTrail,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.AJAX,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.ValerypopoffTouchPlusPlugin,
		C3.Plugins.NinePatch,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Mouse,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.NinePatch.Cnds.HasTags,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Dictionary.Cnds.ForEachKey,
		C3.Plugins.Dictionary.Exps.CurrentKey,
		C3.Plugins.Dictionary.Exps.CurrentValue,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Json.Cnds.IsBooleanSet,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Eponesh_GameScore.Exps.Language,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Arr.Exps.CurX,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Behaviors.Physics.Exps.Density,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Json.Exps.CurrentValue,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Keyboard.Exps.StringFromKeyCode,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Exps.anglediff,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Keyboard.Exps.LastKeyCode,
		C3.Plugins.Keyboard.Cnds.IsKeyCodeDown,
		C3.Plugins.Sprite.Exps.TagAt,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.HasChildren,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.skymenTrail.Acts.SetWidthEnd,
		C3.Behaviors.skymenTrail.Acts.SetLength,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Behaviors.skymenTrail.Acts.SetWidthStart,
		C3.Behaviors.skymenTrail.Acts.Attach,
		C3.Behaviors.skymenTrail.Acts.Reset,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.AdvancedRandom.Exps.WeightedByName,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.NinePatch.Cnds.OnCreated,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.Text.Acts.SetAngle,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Exps.TagAt,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Cnds.IsOnLayer,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Text.Cnds.PickParent,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Json.Acts.DeleteKey,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.ChangeTags,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.NinePatch.Acts.AddInstanceVar,
		C3.Plugins.NinePatch.Exps.TagAt,
		C3.Plugins.TiledBg.Cnds.PickChildren,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Json.Acts.SetBoolean,
		C3.Plugins.Json.Acts.PushValue,
		C3.Plugins.Json.Acts.RemoveValues,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.Json.Acts.SetArray,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.MoveToBottom,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTableFromJSON
	];
};
self.C3_JsPropNameTable = [
	{Game: 0},
	{Map: 0},
	{TeamsScore: 0},
	{PlayersData: 0},
	{Team: 0},
	{Physics: 0},
	{Ring1: 0},
	{Ring2: 0},
	{RingCollision: 0},
	{WithStand: 0},
	{RingSpawn: 0},
	{ID: 0},
	{BallTrigger: 0},
	{Picked: 0},
	{RingID: 0},
	{LastImpulseX: 0},
	{LastImpulseY: 0},
	{Tween: 0},
	{Pin: 0},
	{Timer: 0},
	{DragDrop: 0},
	{Ball: 0},
	{BallParticles: 0},
	{BallSprite: 0},
	{Clr: 0},
	{TrailRenderer: 0},
	{BallTrail: 0},
	{Basket_Stand: 0},
	{Wall: 0},
	{Wall2: 0},
	{BG_Zone: 0},
	{BG_Road: 0},
	{BG_Fence: 0},
	{BG_Clouds: 0},
	{BG_Grass: 0},
	{ScaleX: 0},
	{ScaleY: 0},
	{ScaleAll: 0},
	{Angle1: 0},
	{AnimAngle: 0},
	{Rising: 0},
	{Sine: 0},
	{Player_Arm: 0},
	{Player_Head: 0},
	{Flying: 0},
	{Mirrored: 0},
	{FlyingTimer: 0},
	{StartFly: 0},
	{Controls: 0},
	{Landing: 0},
	{StartX: 0},
	{StartY: 0},
	{FlyingTimerTo: 0},
	{Player_Torso: 0},
	{Player_Feet: 0},
	{Scroll: 0},
	{StartScale: 0},
	{CurScale: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Anchor: 0},
	{Mobile_Controls: 0},
	{Ru: 0},
	{En: 0},
	{TextEndGame: 0},
	{TextGoal: 0},
	{TextScore: 0},
	{TextEndGame2: 0},
	{Flash: 0},
	{TextChooseKey: 0},
	{TextNOTIFICATION: 0},
	{TextKeyToPress: 0},
	{TextPause: 0},
	{TextKeyToPress2: 0},
	{TextKeyToPress3: 0},
	{TextKeyToPress4: 0},
	{Index: 0},
	{TextModificators: 0},
	{TextMapMenu: 0},
	{TextSkinPrice: 0},
	{SizeX: 0},
	{SizeY: 0},
	{Enabled: 0},
	{Touched: 0},
	{Button: 0},
	{Button_Icon: 0},
	{UIBack: 0},
	{Keyboard: 0},
	{AJAX: 0},
	{Touch: 0},
	{Browser: 0},
	{secret: 0},
	{ValerypopoffTouchPlus: 0},
	{Sprite: 0},
	{Data: 0},
	{Sprite2: 0},
	{MESSAGE_Shadow: 0},
	{TiledBackground: 0},
	{Sprite3: 0},
	{Counter: 0},
	{"9patch": 0},
	{LocalStorage: 0},
	{Text: 0},
	{PlatformInfo: 0},
	{sizex: 0},
	{sizey: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Type: 0},
	{Sprite6: 0},
	{Modificatorsg: 0},
	{Modificators: 0},
	{ModificatorsList: 0},
	{TiledBackground2: 0},
	{ScrollTouchY: 0},
	{ScrollMaxPos: 0},
	{ScrollMinPos: 0},
	{Speed: 0},
	{MouseScroll: 0},
	{ScrollPos: 0},
	{Horizontal: 0},
	{Mouse: 0},
	{Sprite7: 0},
	{UI: 0},
	{AdvancedRandom: 0},
	{RandomModificatorsList: 0},
	{ModificatorIDtoIndex: 0},
	{Fade1: 0},
	{MapsMode: 0},
	{MapPreview: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Color1: 0},
	{Color2: 0},
	{Color3: 0},
	{Color4: 0},
	{Stage: 0},
	{R: 0},
	{G: 0},
	{B: 0},
	{TiledBackground3: 0},
	{Saves: 0},
	{GamePush: 0},
	{Player: 0},
	{Texts: 0},
	{Mode: 0},
	{Secret: 0},
	{Outline: 0},
	{TimerSync: 0},
	{Gravity: 0},
	{DefaultGravity: 0},
	{Pause: 0},
	{VelocityX: 0},
	{VelocityY: 0},
	{Control: 0},
	{Var1: 0},
	{Count: 0},
	{Online: 0},
	{Local: 0},
	{overEdgeResponce: 0},
	{sensibility: 0},
	{TimeF: 0},
	{SelectedMenu: 0},
	{Layer: 0},
	{WaitTime: 0},
	{Key: 0},
	{TimeTw: 0},
	{X: 0},
	{XSpawn: 0},
	{XSpawn2: 0}
];

self.InstanceType = {
	Game: class extends self.IJSONInstance {},
	Map: class extends self.IJSONInstance {},
	TeamsScore: class extends self.IDictionaryInstance {},
	PlayersData: class extends self.IArrayInstance {},
	Ring1: class extends self.ISpriteInstance {},
	Ring2: class extends self.ISpriteInstance {},
	RingCollision: class extends self.ISpriteInstance {},
	RingSpawn: class extends self.ISpriteInstance {},
	BallTrigger: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	BallParticles: class extends self.IParticlesInstance {},
	BallSprite: class extends self.ISpriteInstance {},
	BallTrail: class extends self.ISpriteInstance {},
	Basket_Stand: class extends self.ISpriteInstance {},
	Wall: class extends self.ISpriteInstance {},
	Wall2: class extends self.ISpriteInstance {},
	BG_Zone: class extends self.ISpriteInstance {},
	BG_Road: class extends self.ITiledBackgroundInstance {},
	BG_Fence: class extends self.ITiledBackgroundInstance {},
	BG_Clouds: class extends self.ITiledBackgroundInstance {},
	BG_Grass: class extends self.ITiledBackgroundInstance {},
	Player_Arm: class extends self.ISpriteInstance {},
	Player_Head: class extends self.ISpriteInstance {},
	Player_Torso: class extends self.ISpriteInstance {},
	Player_Feet: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	Mobile_Controls: class extends self.ISpriteInstance {},
	TextEndGame: class extends self.ITextInstance {},
	TextGoal: class extends self.ITextInstance {},
	TextScore: class extends self.ITextInstance {},
	TextEndGame2: class extends self.ITextInstance {},
	TextChooseKey: class extends self.ITextInstance {},
	TextNOTIFICATION: class extends self.ITextInstance {},
	TextKeyToPress: class extends self.ITextInstance {},
	TextPause: class extends self.ITextInstance {},
	TextKeyToPress2: class extends self.ITextInstance {},
	TextKeyToPress3: class extends self.ITextInstance {},
	TextKeyToPress4: class extends self.ITextInstance {},
	TextModificators: class extends self.ITextInstance {},
	TextMapMenu: class extends self.ITextInstance {},
	TextSkinPrice: class extends self.ITextInstance {},
	Button: class extends self.ISpriteInstance {},
	Button_Icon: class extends self.ISpriteInstance {},
	UIBack: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	secret: class extends self.ISpriteInstance {},
	ValerypopoffTouchPlus: class extends self.IInstance {},
	Tween: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Data: class extends self.IJSONInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	MESSAGE_Shadow: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	LocalStorage: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	PlatformInfo: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Modificatorsg: class extends self.IArrayInstance {},
	Modificators: class extends self.IJSONInstance {},
	ModificatorsList: class extends self.IArrayInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Scroll: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	UI: class extends self.ISpriteInstance {},
	AdvancedRandom: class extends self.IInstance {},
	RandomModificatorsList: class extends self.IArrayInstance {},
	ModificatorIDtoIndex: class extends self.IDictionaryInstance {},
	Fade1: class extends self.ISpriteInstance {},
	MapsMode: class extends self.IArrayInstance {},
	MapPreview: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Saves: class extends self.IJSONInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	Player: class extends self.ISpriteInstance {},
	Texts: class extends self.ITextInstance {}
}